# Generated by Django 3.1 on 2021-12-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='diary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='diary_app.diary'),
            preserve_default=False,
        ),
    ]
