# Generated by Django 3.1 on 2021-12-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0002_events_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
